export const styles = {
  imageQueue: {
    minWidth: '100%',
    maxWidth: '1400px',
    margin: '20px auto 0',
    backgroundColor: '#f0f0f0',
    padding: '20px',
    boxSizing: 'border-box' as const,
    borderRadius: '8px',
  },
  queueTitle: {
    marginBottom: '16px',
    fontSize: '18px',
  },
  queueList: {
    margin: 0,
  },
  queueItem: {
    cursor: 'pointer',
    transition: 'transform 0.2s ease',
  },
  queueItemHover: {
    cursor: 'pointer',
    transition: 'transform 0.2s ease',
    transform: 'translateY(-2px)',
  },
  queueItemActive: {
    cursor: 'pointer',
    transition: 'transform 0.2s ease',
    transform: 'translateY(-2px)',
  },
  queueItemContent: {
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'center',
    textAlign: 'center' as const,
    padding: '8px',
    backgroundColor: 'white',
    borderRadius: '6px',
    boxShadow: '0 1px 3px rgba(0, 0, 0, 0.1)',
    transition: 'box-shadow 0.2s ease',
  },
  queueItemContentHover: {
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'center',
    textAlign: 'center' as const,
    padding: '8px',
    backgroundColor: 'white',
    borderRadius: '6px',
    boxShadow: '0 2px 8px rgba(0, 0, 0, 0.15)',
    transition: 'box-shadow 0.2s ease',
  },
  queueItemContentActive: {
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'center',
    textAlign: 'center' as const,
    padding: '8px',
    backgroundColor: 'white',
    borderRadius: '6px',
    boxShadow: '0 2px 8px rgba(0, 0, 0, 0.15)',
    transition: 'box-shadow 0.2s ease',
    border: '3px solid #52c41a',
  },
  queueItemImage: {
    marginBottom: '8px',
    backgroundColor: '#f5f5f5',
    borderRadius: '6px',
    overflow: 'hidden',
  },
  imagePlaceholder: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    height: '100%',
    backgroundColor: '#f5f5f5',
    color: '#999',
    fontSize: '24px',
  },
  previewMask: {
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    color: 'white',
    fontSize: '12px',
    borderRadius: '4px',
  },
  queueItemName: {
    fontSize: '12px',
    color: '#666',
    fontWeight: 500,
  },
};
